@startuml
!include <archimate/Archimate>
sprite $bProduct jar:archimate/business-product

Application_Service(strava, "<<external>>\nStrava")
Application_DataObject(klubbdata, "<<external>>\nHdir club")

archimate #Business "Scraper" as bscraper<<business-service>>
'Application_Component(action, "action script")
Application_Component(scraper, "strava-club-scraper.py")
'action -down-> scraper
'bscraper -down- action
'rectangle "data branch" {
Business_Service(bbehandler, "Databehandler")
Application_DataObject(csvres, "club_leaderboard.csv")
Application_DataObject(csvdelt, "club_members.csv")
Application_Component(behandler, "Databehandler")
Application_DataObject(resjson, "result.json")
Application_DataObject(info, "info.md")
Application_Service(jtd, "Just-the-docs")
'Application_DataObject(csvtot, "totalresultat.json")
'Application_DataObject(akk, "club_accumulated.json")
'}

Business_Service(bpresent, "Presentere")
Application_Component(present, "Presentatør")
Application_DataObject(results, "index.md")
rectangle "gh-pages\nbranch" {
  Application_DataObject(websider, "Websider")
}

'note "All kildekoden\nligger i main branch" as kildekode
'kildekode -up- scraper
'kildekode -up- behandler
'kildekode -up- present

strava -right[hidden]- bscraper
strava -down-> klubbdata
klubbdata -right-> scraper
bscraper -down- scraper
bscraper -right[hidden]- bbehandler
bbehandler -down- behandler
scraper -up-> csvres
scraper -right-> csvdelt
csvres -down[hidden]- csvdelt
csvres -right-> behandler
csvdelt -right-> behandler
'resjson -down[hidden]- csvtot
'csvtot -down[hidden]- akk
behandler -right-> resjson
resjson -left-> behandler
resjson -right-> present
resjson -down[hidden]- info
results -down-> jtd
'csvtot -right-> present
'akk -right-> present
bpresent -down- present
present -right-> results
info -right-> jtd
jtd -right-> websider

@enduml