## GitHub Actions Workflow
# Last update: 2024-01-25

# Save this file to '.github/workflows/github-actions-workflow.yaml'

# Name of the workflow
name: Teste just the docs
# Get strava user and password into the environment from Github secrets.
env:
  STRAVA_USER: ${{ secrets.STRAVA_USER }}
  STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
# Controls on when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    # Type of machine to run the job on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository content - https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
         ref: 'test'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      
          - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: ./TestBuildJTD